### ISSUE TITLE
ImportError: cannot import name 'MCBModel' from 'models'

### ISSUE THREAD

**Issue by xincob** [syvlo/RSVQA#2]
This error occurs when I run the "train. py" file. I also didn‘t find this class in "model. py".

**Comment by syvlo** [comment]
Hello,
Thanks for letting me know. This was a reference to a model that we tried but decided not to keep in the release. It can be safely discarded. I did a commit that remove the reference, it should be all good with the last version.
Best,
Sylvain Lobry
